client_config_backend: settings
client_config:
  client_id: X
  client_secret: X

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True
